# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16ic4bzs6yaGXah-970cnIvICoSk_SAq9
"""

user_name = print("Enter user name")
print("Display ticket type")
print("Regular == 500")
print("VIP == 1000")
ticket_type = input("Enter ticket type")
number_of_tickets = input("Enter number of tickets")

total_price = int(number_of_tickets)*500
print("total_price")

if total > 3000:
  print("10% discount")

total = print("total + final amount")